export const THEMES = {
  light: {
    id: "light",
    name: "Light",
    layout: "classic",
    vars: {
      "--bg": "#f9fafb",
      "--bg-card": "#ffffff",
      "--text": "#111827",
      "--text-secondary": "#6b7280",
      "--text-muted": "#9ca3af",
      "--border": "#e5e7eb",
      "--link-bg": "#ffffff",
      "--link-hover": "#f3f4f6",
      "--link-border": "#e5e7eb",
      "--link-radius": "0.5rem",
      "--link-shadow": "0 1px 2px rgba(0,0,0,0.05)",
      "--avatar-bg": "#e5e7eb",
    },
  },
  dark: {
    id: "dark",
    name: "Dark",
    layout: "classic",
    vars: {
      "--bg": "#0f172a",
      "--bg-card": "#1e293b",
      "--text": "#f1f5f9",
      "--text-secondary": "#94a3b8",
      "--text-muted": "#64748b",
      "--border": "#334155",
      "--link-bg": "#1e293b",
      "--link-hover": "#334155",
      "--link-border": "#334155",
      "--link-radius": "0.5rem",
      "--link-shadow": "0 1px 3px rgba(0,0,0,0.3)",
      "--avatar-bg": "#334155",
    },
  },
  ocean: {
    id: "ocean",
    name: "Ocean",
    layout: "card",
    vars: {
      "--bg": "#0c4a6e",
      "--bg-card": "#ffffff",
      "--text": "#0c4a6e",
      "--text-secondary": "#0369a1",
      "--text-muted": "#7dd3fc",
      "--border": "#bae6fd",
      "--link-bg": "#e0f2fe",
      "--link-hover": "#bae6fd",
      "--link-border": "#7dd3fc",
      "--link-radius": "0.75rem",
      "--link-shadow": "none",
      "--avatar-bg": "#bae6fd",
    },
  },
  sunset: {
    id: "sunset",
    name: "Sunset",
    layout: "cover",
    vars: {
      "--bg": "linear-gradient(135deg, #fbbf24, #f97316, #ef4444)",
      "--bg-solid": "#fef3c7",
      "--bg-card": "#fffbeb",
      "--text": "#78350f",
      "--text-secondary": "#92400e",
      "--text-muted": "#d97706",
      "--border": "#fde68a",
      "--link-bg": "#fffbeb",
      "--link-hover": "#fef3c7",
      "--link-border": "#fde68a",
      "--link-radius": "9999px",
      "--link-shadow": "0 2px 4px rgba(0,0,0,0.1)",
      "--avatar-bg": "#fde68a",
    },
  },
  forest: {
    id: "forest",
    name: "Forest",
    layout: "card",
    vars: {
      "--bg": "#064e3b",
      "--bg-card": "#ecfdf5",
      "--text": "#064e3b",
      "--text-secondary": "#047857",
      "--text-muted": "#6ee7b7",
      "--border": "#a7f3d0",
      "--link-bg": "#ecfdf5",
      "--link-hover": "#d1fae5",
      "--link-border": "#a7f3d0",
      "--link-radius": "0.5rem",
      "--link-shadow": "none",
      "--avatar-bg": "#a7f3d0",
    },
  },
  lavender: {
    id: "lavender",
    name: "Lavender",
    layout: "card",
    vars: {
      "--bg": "#4c1d95",
      "--bg-card": "#f5f3ff",
      "--text": "#4c1d95",
      "--text-secondary": "#6d28d9",
      "--text-muted": "#c4b5fd",
      "--border": "#ddd6fe",
      "--link-bg": "#ede9fe",
      "--link-hover": "#ddd6fe",
      "--link-border": "#c4b5fd",
      "--link-radius": "0.75rem",
      "--link-shadow": "none",
      "--avatar-bg": "#ddd6fe",
    },
  },
  blush: {
    id: "blush",
    name: "Blush",
    layout: "classic",
    vars: {
      "--bg": "#fdf2f8",
      "--bg-card": "#ffffff",
      "--text": "#831843",
      "--text-secondary": "#be185d",
      "--text-muted": "#f9a8d4",
      "--border": "#fbcfe8",
      "--link-bg": "#fce7f3",
      "--link-hover": "#fbcfe8",
      "--link-border": "#f9a8d4",
      "--link-radius": "0.75rem",
      "--link-shadow": "none",
      "--avatar-bg": "#fbcfe8",
    },
  },
  cyberpunk: {
    id: "cyberpunk",
    name: "Cyberpunk",
    layout: "cover",
    vars: {
      "--bg": "#0a0a0a",
      "--bg-card": "#18181b",
      "--text": "#22d3ee",
      "--text-secondary": "#a5f3fc",
      "--text-muted": "#164e63",
      "--border": "#22d3ee",
      "--link-bg": "#18181b",
      "--link-hover": "#27272a",
      "--link-border": "#22d3ee",
      "--link-radius": "0",
      "--link-shadow": "0 0 8px rgba(34,211,238,0.3)",
      "--avatar-bg": "#164e63",
    },
  },
};

export const THEME_IDS = Object.keys(THEMES);

export function getTheme(themeId) {
  return THEMES[themeId] || THEMES.light;
}
